---
defaults:
  - _self_

dataset:
  n_nodes: 100
  n_graphs: 1000
  generation_key: 0
  split_key: 0

model:
  hidden_dim: 128
  n_layers: 5
  conv_type: "gat"  # "gat" or "sum"
  key: 66

trainer:
  learning_rate: 3e-4
  batch_size: 16
  train_iter: 50000
  eval_iter: 20
  eval_freq: 100
  key: 42

wandb:
  entity: pierrotlc
  group: none
  mode: ${..mode}

mode: offline

hydra:
  job:
    chdir: true
