---
defaults:
  - _self_

dataset:
  n_nodes: 100
  n_graphs: 1000
  generation_key: 0
  split_key: 1

model:
  hidden_dim: 92
  n_layers: 4
  key: 66

trainer:
  learning_rate: 3e-5
  batch_size: 32
  train_iter: 10000
  eval_iter: 20
  eval_freq: 100
  key: 42

wandb:
  entity: pierrotlc
  group: none
  mode: ${..mode}

mode: offline

hydra:
  job:
    chdir: true
